version: '3'
services:
  docker_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
    ports:
      - "3306:3306"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - docker_db
    command: 
      - sh
      - -c
      - "cd /app/backend/migrations && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && cd .. && npm start"

  test_backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.test  
    depends_on:
      - backend
      - docker_db
    command:
      - sh
      - -c
      - "npm run test"
  
  test_frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.test
    depends_on:
      - backend
      - docker_db
    command: 
      - sh
      - -c
      - "npm run test "
  
