# Dockerfile.test-backend

# Utiliza una imagen base de Node
FROM node:18-alpine

# Establece el directorio de trabajo para el backend
WORKDIR /app/backend

# Copia todos los archivos necesarios para el backend
COPY backend .

# Instala dependencias
RUN npm install --only=dev

# Comando para ejecutar las pruebas